# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all

Admin.destroy_all
Admin.create({first_name: "Peter", last_name: "Hahn", email: "peter.hahn@live.com", password: "cat123"})
Admin.create({first_name: "Lisa", last_name: "Yoo", email: "eunlisa61@yahoo.com", password: "crystaltimothy"})
Admin.create({first_name: "Crystal", last_name: "Yoo", email: "suejung88@gmail.com", password: "animals"})

Menu.destroy_all
Menu.create({course: "Appetizers", dish_name: "Cherrystone Clams On The Half Shell(6)", description: "", price: "$4.99"})
Menu.create({course: "Appetizers", dish_name: "Littlenck Clams On The Half Shell(6)", description: "", price: "$4.99"})
Menu.create({course: "Appetizers", dish_name: "Steamed Littleneck Clams(12)", description: "(butter, broth, Lemon)", price: "$9.99"})
Menu.create({course: "Appetizers", dish_name: "Clams Casino(4)", description: "", price: "$4.99"})
Menu.create({course: "Appetizers", dish_name: "Stuffed Mushrooms Caps with Crab Meat(5)", description: "", price: "$4.99"})
Menu.create({course: "Appetizers", dish_name: "Stuffed Mushrooms/Clam Casino Combo", description: "", price: "$4.99"})
Menu.create({course: "Appetizers", dish_name: "Cocktail Shrimp (10 Large)", description: "w/ Cocktail Sauce & Lemon Wedge", price: "$4.25"})
Menu.create({course: "Appetizers", dish_name: "Cocktail Shrimp (6 Jumbo)", description: "w/ Cocktail Sauce & Lemon Wedge", price: "$7.25"})
Menu.create({course: "Appetizers", dish_name: "Steamed Mussel(2LB)", description: "Red or Garlic and Butter", price: "$19.99"})
Menu.create({course: "Appetizers", dish_name: "Jumbo Whole Wings(ea)", description: "", price: "$1.50"})
Menu.create({course: "Appetizers", dish_name: "Buffalo Wings(10)", description: "BBQ or Hot & Spicy or mild", price: "$7.99"})
Menu.create({course: "Appetizers", dish_name: "Buffalo Wings(20)", description: "BBQ or Hot & Spicy or mild", price: "$15.50"})
Menu.create({course: "Appetizers", dish_name: "Buffalo Wings(30)", description: "BBQ or Hot & Spicy or mild", price: "$23.00"})
Menu.create({course: "Appetizers", dish_name: "Buffalo Wings(40)", description: "BBQ or Hot & Spicy or mild", price: "$30.00"})
Menu.create({course: "Appetizers", dish_name: "Buffalo Wings - Party Tray", description: "BBQ or Hot & Spicy or mild (includes Celery Stix, Carrot Stix, Clue Cheese)", price: "add $8.00"})
Menu.create({course: "Appetizers", dish_name: "Celery Stix", description: "BBQ or Hot & Spicy or mild", price: "$.60"})
Menu.create({course: "Appetizers", dish_name: "Celery Stix", description: "", price: "$.60"})
Menu.create({course: "Appetizers", dish_name: "Blue Cheese", description: "", price: "$.60"})
Menu.create({course: "Appetizers", dish_name: "Chicken Nuggets - Chicken Breaded(6)", description: "", price: "$3.50"})
Menu.create({course: "Appetizers", dish_name: "Chicken Nuggets - Chicken Breaded(12)", description: "", price: "$6.50"})
Menu.create({course: "Appetizers", dish_name: "Mozzarella Stick(6)", description: "Breaded cheese fried to perfection.  Comes w/ our own Marinara sauce", price: "$4.50"})
Menu.create({course: "Appetizers", dish_name: "Fried Chicken(4 pc.)", description: "", price: "$6.99"})
Menu.create({course: "Appetizers", dish_name: "Fried Chicken(8 pc.)", description: "", price: "$13.50"})
Menu.create({course: "Appetizers", dish_name: "Fried Chicken(12 pc.)", description: "", price: "$19.99"})
Menu.create({course: "Appetizers", dish_name: "Fried Chicken(16 pc.)", description: "", price: "$26.50"})
Menu.create({course: "Appetizers", dish_name: "Chicken Noodle Soup(Pt.)", description: "", price: "$3.99"})
Menu.create({course: "Appetizers", dish_name: "Chicken Noodle Soup(Qt.)", description: "", price: "$7.50"})
Menu.create({course: "Appetizers", dish_name: "Manhattan Clam Chowder(Pt.)", description: "", price: "$3.99"})
Menu.create({course: "Appetizers", dish_name: "Manhattan Clam Chowder(Qt.)", description: "", price: "$7.50"})
Menu.create({course: "Appetizers", dish_name: "New England Clam Chowder(Pt.)", description: "", price: "$3.99"})
Menu.create({course: "Appetizers", dish_name: "New England Clam Chowder(Qt.)", description: "", price: "$7.50"})
Menu.create({course: "Appetizers", dish_name: "Genuine Snapper with Sherry(Pt.)", description: "", price: "$3.99"})
Menu.create({course: "Appetizers", dish_name: "Genuine Snapper with Sherry(Qt.)", description: "", price: "$7.50"})
Menu.create({course: "Appetizers", dish_name: "Fresh Oyster Stew(Pt.)", description: "", price: "$4.99"})
Menu.create({course: "Appetizers", dish_name: "Fresh Oyster Stew(Qt.)", description: "", price: "$8.50"})
Menu.create({course: "Appetizers", dish_name: "Fresh Clam Stew(Pt.)", description: "", price: "$3.99"})
Menu.create({course: "Appetizers", dish_name: "Fresh Clam Stew(Qt.)", description: "", price: "$7.50"})

Menu.create({course: "Vegetables", dish_name: "French Fries", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Onion Rings", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Eggplant", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Apple Sauce", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Baked Potato", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Mashed Potato", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Broccoli", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Green Beans", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Cole Slaw", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Potato Salad", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Macaroni Salad", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Mushrooms", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Pickled Beets", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Stewed Tomato", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Pasta Salad", description: "", price: ""})
Menu.create({course: "Vegetables", dish_name: "Corn on The Cob", description: "", price: ""})

Menu.create({course: "Fried Platters", dish_name: "21 Shrimp in a Basket", description: "", price: "$8.99"})
Menu.create({course: "Fried Platters", dish_name: "Deluxe Combination", description: "Includes Flounder, Shrimp, Deviled Crab, Deviled Clam, Scallops. Fish Cake", price: "$16.99"})
Menu.create({course: "Fried Platters", dish_name: "Jumbo Shrimp(6)", description: "", price: "$10.99"})
Menu.create({course: "Fried Platters", dish_name: "Fresh Flounder Filet (1/2 lb.)", description: "", price: "$10.99"})
Menu.create({course: "Fried Platters", dish_name: "Fresh Sea Scallops (1/2 lb.)", description: "", price: "$13.99"})
Menu.create({course: "Fried Platters", dish_name: "Deluxe Maryland Deviled Crabs(2)", description: "", price: "$9.99"})
Menu.create({course: "Fried Platters", dish_name: "Jumbo Shrimp(3), Sea Scallops (1/4 lb.) Combo", description: "", price: "$12.99"})
Menu.create({course: "Fried Platters", dish_name: "Large Butterfly Shirmp(8)", description: "", price: "$9.99"})
Menu.create({course: "Fried Platters", dish_name: "Large Butterfly Shirmp(12)", description: "", price: "$13.99"})
Menu.create({course: "Fried Platters", dish_name: "Fresh Stuffed Shrimp with Crabmeat(2)", description: "", price: "$10.99"})
Menu.create({course: "Fried Platters", dish_name: "Fresh Flounder Filet Stuffed with Crabmeat(2)", description: "", price: "$13.99"})
Menu.create({course: "Fried Platters", dish_name: "Hearty Deviled Clams(3)", description: "", price: "$8.99"})
Menu.create({course: "Fried Platters", dish_name: "Large Prime Oysters(3)", description: "", price: "$10.99"})
Menu.create({course: "Fried Platters", dish_name: "Home Style Fish Cakes(3)", description: "", price: "$8.99"})
Menu.create({course: "Fried Platters", dish_name: "Fried Clam Strips (1/2 lb.)", description: "", price: "$6.99"})
Menu.create({course: "Fried Platters", dish_name: "Fried Boneless Chicken Tender(1/2 lb.)", description: "", price: "$7.99"})
Menu.create({course: "Fried Platters", dish_name: "Shrimp Feast Dinner", description: "1/4 lb. Shrimp Salad, 2 Fried Srimp, 2 Cooked Shrimp, 1 Fried Stuffed Shrimp, 1 Shrimp Roll", price: "$15.99"})
Menu.create({course: "Fried Platters", dish_name: "Soft Shell Crab(2)", description: "", price: "$15.99"})
Menu.create({course: "Fried Platters", dish_name: "Whiting(1/2 lb.)", description: "", price: "$7.99"})
Menu.create({course: "Fried Platters", dish_name: "Jumbo Whole Wings(3)", description: "", price: "$6.99"})
Menu.create({course: "Fried Platters", dish_name: "Fried Chicken 4 PC. Platter", description: "", price: "$8.99"})

Menu.create({course: "Broiled Platters", dish_name: "Snow Crab(1 lb.)", description: "", price: "$17.99"})
Menu.create({course: "Broiled Platters", dish_name: "Fresh Flounder", description: "", price: "$12.99"})
Menu.create({course: "Broiled Platters", dish_name: "Salmon Filet", description: "", price: "$11.99"})
Menu.create({course: "Broiled Platters", dish_name: "Stuffed Filet of Flounder", description: "", price: "$15.99"})
Menu.create({course: "Broiled Platters", dish_name: "Broiled Jumbo Shrimp(7)", description: "", price: "$13.99"})
Menu.create({course: "Broiled Platters", dish_name: "Broiled Stuffed Shrimp(3)", description: "", price: "$15.99"})
Menu.create({course: "Broiled Platters", dish_name: "Broiled Deluxe Combo", description: "4 oz. Lobster Tail, Stuffed Shrimp, Filet of Flounder, Scallops, Shrimp, Clam Casino", price: "$29.99"})
Menu.create({course: "Broiled Platters", dish_name: "Fresh Scallops(1/2 lb.)", description: "", price: "$14.99"})
Menu.create({course: "Broiled Platters", dish_name: "Broiled Lobster Tail(9 oz.)", description: "", price: "$22.99"})
Menu.create({course: "Broiled Platters", dish_name: "Broiled Combo", description: "1/4 lb. Flounder, 1/4 lb. Scallop, 3 Broiled Shrimp", price: "$16.99"})
Menu.create({course: "Broiled Platters", dish_name: "Alaskan King Crab Legs(1 lb.)", description: "", price: "$29.99"})
Menu.create({course: "Broiled Platters", dish_name: "Cajun Catfish", description: "", price: "$11.99"})
Menu.create({course: "Broiled Platters", dish_name: "Orange Roughy", description: "", price: "$12.99"})
Menu.create({course: "Broiled Platters", dish_name: "Seafood Combo Over Pasta", description: "Mussels, Shrimp, Scallop, Clams with Roll and Butter (Choice: Spicy Red Sauce or Garlic White Sauce)", price: "$17.99"})

Menu.create({course: "Cold Platters", dish_name: "Fried Shrimp - Cooked Shrimp Combo", description: "", price: "$10.99"})
Menu.create({course: "Cold Platters", dish_name: "Jumbo Cooked Cocktail Shrimp(6)", description: "", price: "$10.99"})
Menu.create({course: "Cold Platters", dish_name: "Tuna Salad", description: "", price: "$6.99"})
Menu.create({course: "Cold Platters", dish_name: "Shrimp Salad", description: "", price: "$7.99"})
Menu.create({course: "Cold Platters", dish_name: "Seafood Salad", description: "", price: "$6.99"})

Menu.create({course: "A La Carte", dish_name: "Large Fried Butterfly Shrimp(8)", description: "", price: "$6.99"})
Menu.create({course: "A La Carte", dish_name: "Large Fried Butterfly Shrimp(15)", description: "", price: "$12.99"})
Menu.create({course: "A La Carte", dish_name: "Large Fried Butterfly Shrimp(30)", description: "", price: "$24.00"})
Menu.create({course: "A La Carte", dish_name: "Large Fried Butterfly Shrimp(45)", description: "", price: "$33.00"})
Menu.create({course: "A La Carte", dish_name: "Jumbo Fried Shrimp/Coconut Shrimp(6)", description: "", price: "$7.99"})
Menu.create({course: "A La Carte", dish_name: "Jumbo Fried Shrimp/Coconut Shrimp(12)", description: "", price: "$15.00"})
Menu.create({course: "A La Carte", dish_name: "Jumbo Fried Shrimp/Coconut Shrimp(18)", description: "", price: "$22.00"})
Menu.create({course: "A La Carte", dish_name: "Jumbo Fried Shrimp/Coconut Shrimp(24)", description: "", price: "$29.99"})
Menu.create({course: "A La Carte", dish_name: "Fresh Fried Flounder Fillet(per lb.)", description: "", price: "$15.99"})
Menu.create({course: "A La Carte", dish_name: "Deluxe Maryland Deviled Crab(ea.)", description: "", price: "$3.50"})
Menu.create({course: "A La Carte", dish_name: "Hearty Deviled Clams(ea.)", description: "", price: "$1.99"})
Menu.create({course: "A La Carte", dish_name: "Flounder Stuffed with Crabmeat(ea.)", description: "", price: "$4.99"})
Menu.create({course: "A La Carte", dish_name: "Jumbo Shrimp Stuffed with Crabmeat(ea.)", description: "", price: "$3.99"})
Menu.create({course: "A La Carte", dish_name: "Large Prime Fried Oysters(ea.)", description: "", price: "$2.50"})
Menu.create({course: "A La Carte", dish_name: "Fresh Fried Sea Scallops(per lb.)", description: "", price: "$22.99"})
Menu.create({course: "A La Carte", dish_name: "Home Style Fish Cakes(ea.)", description: "", price: "$1.99"})
Menu.create({course: "A La Carte", dish_name: "Fried Clam Strips(per lb.)", description: "", price: "$7.99"})
Menu.create({course: "A La Carte", dish_name: "Chinese Style Shrimp Rolls(ea.)", description: "", price: "$1.75"})
Menu.create({course: "A La Carte", dish_name: "Pizza Roll(ea.)", description: "", price: "$1.75"})
Menu.create({course: "A La Carte", dish_name: "Fried Boneless Chicken Breast(per lb.)", description: "", price: "$10.99"})
Menu.create({course: "A La Carte", dish_name: "Golden Brown Crab Stix(ea.)", description: "", price: "$.85"})
Menu.create({course: "A La Carte", dish_name: "Golden Brown Crab Stix(6)", description: "", price: "$4.99"})
Menu.create({course: "A La Carte", dish_name: "Whiting(per lb.)", description: "", price: "$8.99"})

Menu.create({course: "Specials", dish_name: "Special No. 1", description: "3/4 lb. Fresh Fried Flounder, 10 Jumbo Shrimp, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 4oz. Cocktail or Tartar Sauce", price: "$25.99"})
Menu.create({course: "Specials", dish_name: "Special No. 2", description: "3/4 lb. Fresh Fried Flounder, 6 Tender Fried Sea Scallops, 3 Jumbo Shrimp, 2 Fish Cakes, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 4oz. Cocktail or Tartar Sauce", price: "$25.99"})
Menu.create({course: "Specials", dish_name: "Special No. 3", description: "3/4 lb. Fresh Fried Flouner, 2 Deviled Crabs, 2 Deviled Clams, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 4oz. Cocktail or Tartar Sauce", price: "$23.99"})
Menu.create({course: "Specials", dish_name: "Special No. 4", description: "2 Stuffed Flounder, 6 Fried Jumbo Shrimp, 2 Shrimp Rolls, 1 Order Fried Clams (1/2lb.), 1 pt. Creamy Cole Slaw", price: "$27.99"})
Menu.create({course: "Specials", dish_name: "Special No. 5", description: "3/4 lb. Fresh Fried Flounder, 2 Deviled Crabs, 6 Jumbo Shrimp, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 4oz. Cocktail or Tartar Sauce", price: "$27.99"})
Menu.create({course: "Specials", dish_name: "Special No. 6", description: "3/4 lb. Fresh Fried Flounder, 8 Large Butterfly Shrimp, 2 Deviled Clams, 2 Fish Cakes, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 4oz. Cocktail or Tartar Sauce", price: "$26.99"})
Menu.create({course: "Specials", dish_name: "Special No. 7", description: "1 lb. Fresh Fried Flounder, 8 Jumbo Shrimp, 10 Plump Sea Scallops, 2 Deviled Crabs, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 4oz. Cocktail or Tartar Sauce", price: "$42.99"})
Menu.create({course: "Specials", dish_name: "Special No. 8", description: "3/4 lb. Fresh Fried Flounder, 15 Large Butterfly Shrimp, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 4oz. Cocktail or Tartar Sauce", price: "$25.99"})
Menu.create({course: "Specials", dish_name: "Special No. 9", description: "3/4 lb. Fresh Fried Flounder, 10 Large Butterfly Shrimp, 6 Plump Sea Scallops, 2 Deviled Crabs, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 4oz. Cocktail or Tartar Sauce", price: "$34.99"})
Menu.create({course: "Specials", dish_name: "Special No. 10", description: "1 lb. Fried Boneless Chicken Tender, 15 Large Butterfly Shrimp, 1 Large Order Crisp French Fries, 1pt. Creamy Cole Slaw, 2oz. Cocktail & BBQ Sauce", price: "$23.99"})
Menu.create({course: "Specials", dish_name: "Special For Two - Special A", description: "1/2 lb. Fresh Fried Flouner, 3 Jumbo Shrimp, Small Order Crsip French Fries, 1/2 lb. Creamy Cole Slaw, 2oz. Cocktail or Tartar Sauce", price: "$13.99"})
Menu.create({course: "Specials", dish_name: "Special For Two - Special B", description: "1/2 lb. Fresh Fried Flounder, 3 Jumbo Shrimp, 3 Plump Sea Scallops, 1 Shrimp Roll, Small Order Crsip French Fries, 1/2 lb. Creamy Cole Slaw, 2oz. Cocktail or Tartar Sauce", price: "$16.99"})
Menu.create({course: "Specials", dish_name: "Special For Two - Special C", description: "1/2 lb. Fresh Fried Flounder, 2 Deviled Crabs, 2 Jumbo Shrimp, 2 Tender Sea Scallops, Small Order Crsip French Fries, 1/2 lb. Creamy Cole Slaw, 2oz. Cocktail or Tartar Sauce", price: "$18.99"})
Menu.create({course: "Specials", dish_name: "Shrimp Party Tray", description: "(50) Large Premium Quality Shrimp, Cocktail Sauce, Lemon Wedges, Garnished Serving Tray (Peeled & Deveined)", price: "$43.99"})
Menu.create({course: "Specials", dish_name: "Shrimp Party Tray", description: "(100) Large Premium Quality Shrimp, Cocktail Sauce, Lemon Wedges, Garnished Serving Tray (Peeled & Deveined)", price: "$80.99"})
Menu.create({course: "Specials", dish_name: "Shrimp Party Tray", description: "(50) Jumbo Cocktail Shrimp, Cocktail Sauce, Lemon Wedges, Garnished Serving Tray (Peeled & Deveined)", price: "$65.99"})
Menu.create({course: "Specials", dish_name: "Shrimp Party Tray", description: "(100) Jumbo Cocktail Shrimp, Cocktail Sauce, Lemon Wedges, Garnished Serving Tray (Peeled & Deveined)", price: "$130.99"})
Menu.create({course: "Specials", dish_name: "The Hot Tray", description: "(30) Deviled Crab Balls, (30) Deviled Clam Balls, (30) Chicken Nuggets, (30) Mini Shrimp Rolls, Cocktial Sauce", price: "$80.99"})
Menu.create({course: "Specials", dish_name: "Combo Tray", description: "(50) Large Clean Shrimp, (15) Deviled Crab Miniatures, (15) Deviled Clam Miniatures, (15) Chicken Pieces, (15) Mini Shrimp Rolls", price: "$82.99"})

Menu.create({course: "Lunch", dish_name: "Seafood Salad (Sandwich) (Cold)", description: "", price: "$3.99"})
Menu.create({course: "Lunch", dish_name: "Seafood Salad (Hoagie) (Cold)", description: "", price: "$5.99"})
Menu.create({course: "Lunch", dish_name: "Shrimp Salad (Sandwich) (Cold)", description: "", price: "$4.50"})
Menu.create({course: "Lunch", dish_name: "Shrimp Salad (Hoagie) (Cold)", description: "", price: "$6.50"})
Menu.create({course: "Lunch", dish_name: "Tuna Salad (Sandwich) (Cold)", description: "", price: "$3.99"})
Menu.create({course: "Lunch", dish_name: "Tuna Salad (Hoagie) (Cold)", description: "", price: "$5.99"})
Menu.create({course: "Lunch", dish_name: "Cheese (Sandwich) (Cold)", description: "", price: "$2.99"})
Menu.create({course: "Lunch", dish_name: "Cheese (Hoagie) (Cold)", description: "", price: "$4.99"})
Menu.create({course: "Lunch", dish_name: "Fish Cake (Sandwich) (Fried)", description: "", price: "$5.50"})
Menu.create({course: "Lunch", dish_name: "Fish Cake (Hoagie) (Fried)", description: "", price: "$7.50"})
Menu.create({course: "Lunch", dish_name: "Crab Cake (Sandwich) (Fried)", description: "", price: "$4.50"})
Menu.create({course: "Lunch", dish_name: "Crab Cake (Hoagie) (Fried)", description: "", price: "$8.50"})
Menu.create({course: "Lunch", dish_name: "Flounder (Sandwich) (Fried)", description: "", price: "$4.99"})
Menu.create({course: "Lunch", dish_name: "Flounder (Hoagie) (Fried)", description: "", price: "$7.99"})
Menu.create({course: "Lunch", dish_name: "Chicken Breast (Sandwich) (Fried)", description: "", price: "$4.25"})
Menu.create({course: "Lunch", dish_name: "Chicken Breast (Hoagie) (Fried)", description: "", price: "$7.50"})
Menu.create({course: "Lunch", dish_name: "Oyster (Sandwich) (Fried)", description: "", price: "$5.99"})
Menu.create({course: "Lunch", dish_name: "Oyster (Hoagie) (Fried)", description: "", price: "$9.99"})
Menu.create({course: "Lunch", dish_name: "Whiting (Sandwich) (Fried)", description: "", price: "$3.75"})
Menu.create({course: "Lunch", dish_name: "Whiting (Hoagie) (Fried)", description: "", price: "$6.50"})
Menu.create({course: "Lunch", dish_name: "Steak Sandwich (Hot)", description: "made with fresh onions", price: "$4.99"})
Menu.create({course: "Lunch", dish_name: "Mushroom Cheese Steak (Hot)", description: "", price: "$5.99"})
Menu.create({course: "Lunch", dish_name: "Pizza Steak (Hot)", description: "", price: "$5.99"})
Menu.create({course: "Lunch", dish_name: "Pepper Cheese Steak (Hot)", description: "", price: "$5.99"})
Menu.create({course: "Lunch", dish_name: "Steak Hoagie (Hot)", description: "", price: "$6.99"})
Menu.create({course: "Lunch", dish_name: "Cheese Steak Hoagie(Hot)", description: "", price: "$7.99"})
Menu.create({course: "Lunch", dish_name: "Chicken Steak (Hot)", description: "", price: "$4.99"})
Menu.create({course: "Lunch", dish_name: "Chicken Cheese Steak (Hot)", description: "", price: "$5.50"})
Menu.create({course: "Lunch", dish_name: "Chicken Cheese Steak Hoagie (Hot)", description: "", price: "$7.99"})
Menu.create({course: "Lunch", dish_name: "Crab Cake (Lite Lunch)", description: "All \"Lite Lunch\" include Beverage 12 oz. cans (Non-Alcoholic) and One Vegetable (cole Slaw or French Fries)" , price: "$5.50"})
Menu.create({course: "Lunch", dish_name: "Fish Cake(2) (Lite Lunch)", description: "All \"Lite Lunch\" include Beverage 12 oz. cans (Non-Alcoholic) and One Vegetable (cole Slaw or French Fries)" , price: "$5.99"})
Menu.create({course: "Lunch", dish_name: "Flounder (Lite Lunch)", description: "All \"Lite Lunch\" include Beverage 12 oz. cans (Non-Alcoholic) and One Vegetable (cole Slaw or French Fries)" , price: "$6.50"})
Menu.create({course: "Lunch", dish_name: "Deviled Clam(2) (Lite Lunch)", description: "All \"Lite Lunch\" include Beverage 12 oz. cans (Non-Alcoholic) and One Vegetable (cole Slaw or French Fries)" , price: "$5.99"})

Menu.create({course: "Fresh Fish", dish_name: "Flounder", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Salmon", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Cajun Catfish", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Orange Roughy", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Shrimp", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Sea Scallops", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Stewing Oysters", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Snow Crab Leg", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "King Crab Leg", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Dungeness Crab Leg", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Clams", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Lobster Tail", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Green Shell Mussels", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Soft Shell Crabs", description: "", price: ""})
Menu.create({course: "Fresh Fish", dish_name: "Hard Shell Crabs", description: "", price: ""})

Menu.create({course: "Side Order", dish_name: "French Fries(Sm.)", description: "", price: "$2.50"})
Menu.create({course: "Side Order", dish_name: "French Fries(Lg.)", description: "", price: "$6.50"})
Menu.create({course: "Side Order", dish_name: "Fried Mushrooms(Sm.)", description: "", price: "$3.50"})
Menu.create({course: "Side Order", dish_name: "Fried Mushrooms(Lg.)", description: "", price: "$6.50"})
Menu.create({course: "Side Order", dish_name: "Fried Eggplant(Sm.)", description: "", price: "$3.50"})
Menu.create({course: "Side Order", dish_name: "Fried Eggplant(Lg.)", description: "", price: "$6.50"})
Menu.create({course: "Side Order", dish_name: "Old Fashion Onion Rings(Sm.)", description: "", price: "$3.50"})
Menu.create({course: "Side Order", dish_name: "Old Fashion Onion Rings(Lg.)", description: "", price: "$6.50"})
Menu.create({course: "Side Order", dish_name: "Cheese Fries(Sm.)", description: "", price: "$2.99"})
Menu.create({course: "Side Order", dish_name: "Cheese Fries(Lg.)", description: "", price: "$5.50"})
Menu.create({course: "Side Order", dish_name: "Baked Potato", description: "", price: "$1.99"})
Menu.create({course: "Side Order", dish_name: "Mashed Potato(1/2 lb.)", description: "", price: "$1.99"})
Menu.create({course: "Side Order", dish_name: "Mashed Potato(1 lb.)", description: "", price: "$3.99"})
Menu.create({course: "Side Order", dish_name: "Corn on the Cob", description: "", price: "$1.25"})
Menu.create({course: "Side Order", dish_name: "Cole Slaw", description: "Strictly Fresh Daily", price: "$2.99"})
Menu.create({course: "Side Order", dish_name: "Potato Salad", description: "Strictly Fresh Daily", price: "$2.99"})
Menu.create({course: "Side Order", dish_name: "Macaroni Salad", description: "Strictly Fresh Daily", price: "$2.99"})
Menu.create({course: "Side Order", dish_name: "Pasta Salad", description: "Strictly Fresh Daily", price: "$3.99"})
Menu.create({course: "Side Order", dish_name: "Seafood Slaw", description: "Strictly Fresh Daily", price: "$8.99"})
Menu.create({course: "Side Order", dish_name: "Pickled Beets", description: "Strictly Fresh Daily", price: "$4.99"})
Menu.create({course: "Side Order", dish_name: "Shrimp", description: "Strictly Fresh Daily", price: "$9.99"})
Menu.create({course: "Side Order", dish_name: "Tuna", description: "Strictly Fresh Daily", price: "$8.99"})
Menu.create({course: "Side Order", dish_name: "Apple Sauce", description: "Strictly Fresh Daily", price: "$4.99"})
Menu.create({course: "Side Order", dish_name: "Homemade Cocktail Sauce(4 oz.)", description: "", price: "$.99"})
Menu.create({course: "Side Order", dish_name: "Homemade Cocktail Sauce(2 oz.)", description: "", price: "$.50"})
Menu.create({course: "Side Order", dish_name: "Homemade Tartar Sauce(4 oz.)", description: "", price: "$.99"})
Menu.create({course: "Side Order", dish_name: "Homemade Tartar Sauce(2 oz.)", description: "", price: "$.50"})
Menu.create({course: "Side Order", dish_name: "Homemade Horse Radish(4 oz.)", description: "", price: "$1.25"})
Menu.create({course: "Side Order", dish_name: "Homemade Horse Radish(2 oz.)", description: "", price: "$.69"})
